spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=app-mobile-tcc
spring.datasource.url=${TCC_URL}
spring.datasource.username=${TCC_USERNAME}
spring.datasource.password=${TCC_PASSWORD}

jwt.secret=${TCC_JWT_SECRET}

server.port=8080

spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.docker.compose.enabled=false