services:
  postgres:
    image: 'postgres:18'
    container_name: tcc_bd
    restart: always
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tcc_network

  backend:
    build: .
    container_name: tcc_backend

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    environment:
      TCC_DATASOURCE_URL: ${TCC_DATASOURCE_URL}
      TCC_DATASOURCE_PASSWORD: ${TCC_DATASOURCE_PASSWORD}
      TCC_DATASOURCE_USERNAME: ${TCC_DATASOURCE_USERNAME}
      JWT_SECRET: ${JWT_SECRET}

    networks:
      - tcc_network

volumes:
  postgres_data:

networks:
  tcc_network:



